spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=AIzaSyASjLXRpZz7E-Lkp2E0aXF3FqB95rJHmSQ

